### ISSUE TITLE
下载的Demo启动就闪退

### ISSUE THREAD

**Issue by jiashie** [zhou-you/EasyXRecyclerView#15]
demo包里根本没有各个Activity的代码。。
>Process: com.zhouyou.recyclerviewdemo, PID: 3994
    java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.zhouyou.recyclerviewdemo/com.zhouyou.recyclerview.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "com.zhouyou.recyclerview.MainActivity" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.zhouyou.recyclerviewdemo-YOOPfgOriBUxaX-Gxoi0fg==/base.apk"],nativeLibraryDirectories=[/data/app/com.zhouyou.recyclerviewdemo-YOOPfgOriBUxaX-Gxoi0fg==/lib/arm64, /system/lib64, /product/lib64]]
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3355)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.zhouyou.recyclerview.MainActivity" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.zhouyou.recyclerviewdemo-YOOPfgOriBUxaX-Gxoi0fg==/base.apk"],nativeLibraryDirectories=[/data/app/com.zhouyou.recyclerviewdemo-YOOPfgOriBUxaX-Gxoi0fg==/lib/arm64, /system/lib64, /product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:69)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1224)

**Comment by jhyc** [comment]
闪退+1，我的是华为 honor8 android8
本想看看实际效果。

**Comment by zhou-you** [comment]
是下载的DEMO里面报错吗，还是扫码下载的apk有问题，如果apk有问题，直接下载demo运行吧

**Comment by zhou-you** [comment]
我这边是测试OK了上传的，如果有问题换个手机测试一下，应该是demo的问题，与库无关
